FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y \
    curl \
&& curl -o ~/vsls-reqs https://aka.ms/vsls-linux-prereq-script && chmod +x ~/vsls-reqs && ~/vsls-reqs \
&& apt-get update && apt-get install -y \
    build-essential \
    gdb \
    nasm \
    yasm \
    gcc \
    clang \
    cmake \
    binutils \
    flex \
    bison \
    libyaml-dev \
    pkg-config \
    libssl-dev \
    libpq-dev \
    valgrind \
    libunwind-dev \
    luajit2 \
    git \
    libmsgpack-dev \
    clang \
    dwz \
    gawk \
&& apt-get upgrade -y \
&& rm -rf /var/lib/apt/lists/*

RUN SNIPPET="export PROMPT_COMMAND='history -a' && export HISTFILE=/commandhistory/.bash_history" \
    && echo $SNIPPET >> "/root/.bashrc" \
    # [Optional] If you have a non-root user
    && mkdir /commandhistory \
    && touch /commandhistory/.bash_history \
    && chown -R $(whoami) /commandhistory \
    && mkdir -p "/home/$(whoami)" \
    && echo $SNIPPET >> "/home/$(whoami)/.bashrc"
